version: '3.8'

services:
  notion-chakra-mcp:
    build: .
    ports:
      - "${PORT:-8050}:${PORT:-8050}"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    environment:
      - PORT=${PORT:-8050}
      - HOST=${HOST:-0.0.0.0}
    restart: unless-stopped
    # Any environment variables passed during docker-compose up will override .env values 